// <auto-generated />
using Janus_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Janus_API.Migrations
{
    [DbContext(typeof(Janus_APIContext))]
    [Migration("20220820191639_add_types_and_seed")]
    partial class add_types_and_seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Janus_API.Models.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stock",
                            Name = "Stock"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Crypto Currency",
                            Name = "Crypto"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Stock Options",
                            Name = "Options"
                        },
                        new
                        {
                            Id = 4,
                            Description = "US Dollars",
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Non-fungible tokens",
                            Name = "NFT"
                        });
                });

            modelBuilder.Entity("Janus_API.Models.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Purchase Asset",
                            Name = "Buy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sell Asset",
                            Name = "Sell"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Deposit",
                            Name = "Deposit"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Withdraw",
                            Name = "Withdraw"
                        });
                });

            modelBuilder.Entity("Janus_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Phone1")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Phone2")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
